---
- hosts: localhost
  connection: local

  tasks:
  - name: Run No 802.1x Find script
    shell: python3.6 /home/zjabn3tw/Nodot1x/nodot1x.py > portswithoutdot1x.txt

  - name: Clean up /home/zjabn3tw/Nodot1x/Configs 
    shell: rm -fr /home/zjabn3tw/Nodot1x/Configs/*
   
  - name: Clean up /home/zjabn3tw/Nodot1x/modifiedconfigs 
    shell: rm -fr /home/zjabn3tw/Nodot1x/modifiedconfigs/*

  - name: Send Email
    shell: echo -e "Subject:Ports Without 802.1x" && cat /home/zjabn3tw/Nodot1x/portswithoutdot1x.txt | sendmail joshua.bowers@email.local
